server:
  servlet:
    context-path: "/limit-app"
  port: 8383

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/limits
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-main.yml
    enabled: true
    drop-first: false

limits:
  default-value: 10000.00

scheduler:
  reset-daily-limits-cron: 0 0 0 * * ?